export const CATEGORIES = [
  { id: "Living Room", label: "Living room" },
  { id: "Bedroom", label: "Bedroom" },
  { id: "Bathroom", label: "Bathroom" },
  { id: "Office", label: "Office" },
];

export const PRODUCTS = [
  {
    id: "fluted-sofa",
    slug: "fluted-sofa",
    name: "Fluted Sofa",
    image: "/pick-1.png",
    price: 269.99,
    compareAt: 299.99,
    discount: 10,
    reviews: 123,
    category: "living",
  },
  {
    id: "oak-side-table",
    slug: "oak-side-table",
    name: "Oak Side Table",
    image: "/pick-2.png",
    price: 129.99,
    compareAt: 144.99,
    discount: 10,
    reviews: 123,
    category: "living",
  },
  {
    id: "fluted-couch",
    slug: "fluted-couch",
    name: "Fluted Couch",
    image: "/coffee-tables-img.jpg",
    price: 899.99,
    compareAt: 999.99,
    discount: 10,
    reviews: 123,
    category: "living",
  },
  {
    id: "media-console",
    slug: "media-console",
    name: "Media Console",
    image: "/arm-chair-img.jpg",
    price: 449.99,
    compareAt: 499.99,
    discount: 10,
    reviews: 123,
    category: "living",
  },
];
